In [1]:
import numpy as np
import scipy.stats as stats
import pandas as pd

1) Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks):

zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110],

ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832].

Найдите ковариацию этих двух величин с помощью элементарных действий, а затем с помощью функции cov из numpy

Полученные значения должны быть равны.

Найдите коэффициент корреляции Пирсона с помощью ковариации и среднеквадратичных отклонений двух признаков, а затем с использованием функций из библиотек numpy и pandas.

In [4]:
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [8]:
cov_1 = np.mean(zp * ks) - np.mean(zp) * np.mean(ks)
cov_1

9157.839999999997

In [9]:
cov_2 = np.cov(zp, ks, ddof=0)
cov_2

array([[ 3494.64,  9157.84],
       [ 9157.84, 30468.89]])

In [11]:
r_1 = cov_1 / (np.std(zp) * np.std(ks))
r_1

0.8874900920739158

In [13]:
r_2 = np.corrcoef(zp, ks)
r_2

array([[1.        , 0.88749009],
       [0.88749009, 1.        ]])

In [19]:
d = {'zp': zp, 'ks': ks}
df = pd.DataFrame(data=d)
df

zp   ks
0   35  401
1   45  574
2  190  874
3  200  919
4   40  459
5   70  739
6   54  653
7  150  902
8  120  746
9  110  832

In [22]:
r_3 = df.corr()
r_3

zp       ks
zp  1.00000  0.88749
ks  0.88749  1.00000

2) Измерены значения IQ выборки студентов,

обучающихся в местных технических вузах:

131, 125, 115, 122, 131, 115, 107, 99, 125, 111.

Известно, что в генеральной совокупности IQ распределен нормально.

Найдите доверительный интервал для математического ожидания с надежностью 0.95.

In [23]:
x = np.array([131, 125, 115, 122, 131, 115, 107, 99, 125, 111])
x

array([131, 125, 115, 122, 131, 115, 107,  99, 125, 111])

In [27]:
m_x = np.mean(x)
std_x = np.std(x, ddof=1)

In [28]:
(l, u) = (m_x - stats.norm.ppf(0.975) * std_x / len(x)**0.5, m_x + stats.norm.ppf(0.975) * std_x / len(x)**0.5)
(l, u)

(111.56384743341334, 124.63615256658665)

3) Известно, что рост футболистов в сборной распределен нормально с дисперсией генеральной совокупности, равной 25 кв.см. Объем выборки равен 27, среднее выборочное составляет 174.2. Найдите доверительный интервал для математического ожидания с надежностью 0.95.

In [30]:
D = 25
n = 27
m = 174.2

In [31]:
(l, u) = (m - stats.norm.ppf(0.975) * D**0.5 / n**0.5, m + stats.norm.ppf(0.975) * D**0.5 / n**0.5)
(l, u)

(172.3140237765397, 176.08597622346028)